#!/bin/bash

#:Filename    : install-packages
#:Description : Install packages listed in the "packages" text file
#:Author      : Hai Wu
#:Date        : Nov 08 2024



#storing the name of the packages from the packages file in the variable "packages"
packages=$(cat ./packages)

#prints out the name of the packages being installed 
echo "installing $packages"
  
#installs the packages stored in the variable "packages"
pacman -S $packages
