#!/bin/bash

#: Filename     : sym-links
#: Description  : This script creates symbolic links from the provided configuration files
#: Author       : Hai Wu
#: Date         : Nov 09 2024
#: Version      : 1.0

#: References :

