#!/bin/bash

#: Filename     : sym-links
#: Description  : This script creates symbolic links from the provided configuration files
#: Author       : Hai Wu
#: Date         : Nov 09 2024
#: Version      : 1.0

#: References :


git clone https://gitlab.com/cit2420/2420-as2-starting-files.git
# Clones the configuration files from gitlab


