#!/bin/bash

#: Filename     : new-user
#: Description  : This script creates a new user
#: Author       : Hai Wu
#: Date         : Nov 10 2024
#: Version      : 1.0

#: References :

### Error handling ###
